spring:
#?????? ??
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3305/test?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1111
#jpa??
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

# ???? ??
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
